using System.Text.Json.Serialization;

namespace StrongGrid.Json
{
	[JsonSerializable(typeof(string[]))]
	[JsonSerializable(typeof(long[]))]

	[JsonSerializable(typeof(StrongGrid.Json.StrongGridJsonObject))]
	[JsonSerializable(typeof(StrongGrid.Json.StrongGridJsonObject[]))]

	[JsonSerializable(typeof(StrongGrid.Models.AccessEntry))]
	[JsonSerializable(typeof(StrongGrid.Models.AccessRequest))]
	[JsonSerializable(typeof(StrongGrid.Models.Account))]
	[JsonSerializable(typeof(StrongGrid.Models.AddIpAddressResult))]
	[JsonSerializable(typeof(StrongGrid.Models.AddressWhitelistSettings))]
	[JsonSerializable(typeof(StrongGrid.Models.Alert))]
	[JsonSerializable(typeof(StrongGrid.Models.ApiKey))]
	[JsonSerializable(typeof(StrongGrid.Models.Attachment))]
	[JsonSerializable(typeof(StrongGrid.Models.AuthenticatedDomain))]
	[JsonSerializable(typeof(StrongGrid.Models.AuthenticatedDomainDns))]
	[JsonSerializable(typeof(StrongGrid.Models.BatchInfo))]
	[JsonSerializable(typeof(StrongGrid.Models.BccSettings))]
	[JsonSerializable(typeof(StrongGrid.Models.Block))]
	[JsonSerializable(typeof(StrongGrid.Models.Bounce))]
	[JsonSerializable(typeof(StrongGrid.Models.BouncePurgeSettings))]
	[JsonSerializable(typeof(StrongGrid.Models.BrandedLink))]
	[JsonSerializable(typeof(StrongGrid.Models.BrandedLinkDns))]
	[JsonSerializable(typeof(StrongGrid.Models.ClickTrackingSettings))]
	[JsonSerializable(typeof(StrongGrid.Models.Contact))]
	[JsonSerializable(typeof(StrongGrid.Models.Design))]
	[JsonSerializable(typeof(StrongGrid.Models.DnsRecord))]
	[JsonSerializable(typeof(StrongGrid.Models.DomainValidation))]
	[JsonSerializable(typeof(StrongGrid.Models.DomainValidationResults))]
	[JsonSerializable(typeof(StrongGrid.Models.EmailActivities.BlockedEvent), TypeInfoPropertyName = "EmailActivitiesBlockedEvent")]
	[JsonSerializable(typeof(StrongGrid.Models.EmailActivities.BounceEvent), TypeInfoPropertyName = "EmailActivitiesBounceEvent")]
	[JsonSerializable(typeof(StrongGrid.Models.EmailActivities.ClickEvent), TypeInfoPropertyName = "EmailActivitiesClickEvent")]
	[JsonSerializable(typeof(StrongGrid.Models.EmailActivities.DeferredEvent), TypeInfoPropertyName = "EmailActivitiesDeferredEvent")]
	[JsonSerializable(typeof(StrongGrid.Models.EmailActivities.DeliveredEvent), TypeInfoPropertyName = "EmailActivitiesDeliveredEvent")]
	[JsonSerializable(typeof(StrongGrid.Models.EmailActivities.DroppedEvent), TypeInfoPropertyName = "EmailActivitiesDroppedEvent")]
	[JsonSerializable(typeof(StrongGrid.Models.EmailActivities.Event), TypeInfoPropertyName = "EmailActivitiesEvent")]
	[JsonSerializable(typeof(StrongGrid.Models.EmailActivities.GroupResubscribeEvent), TypeInfoPropertyName = "EmailActivitiesGroupResubscribeEvent")]
	[JsonSerializable(typeof(StrongGrid.Models.EmailActivities.GroupUnsubscribeEvent), TypeInfoPropertyName = "EmailActivitiesGroupUnsubscribeEvent")]
	[JsonSerializable(typeof(StrongGrid.Models.EmailActivities.OpenEvent), TypeInfoPropertyName = "EmailActivitiesOpenEvent")]
	[JsonSerializable(typeof(StrongGrid.Models.EmailActivities.ProcessedEvent), TypeInfoPropertyName = "EmailActivitiesProcessedEvent")]
	[JsonSerializable(typeof(StrongGrid.Models.EmailActivities.SpamReportEvent), TypeInfoPropertyName = "EmailActivitiesSpamReportEvent")]
	[JsonSerializable(typeof(StrongGrid.Models.EmailActivities.UnsubscribeEvent), TypeInfoPropertyName = "EmailActivitiesUnsubscribeEvent")]
	[JsonSerializable(typeof(StrongGrid.Models.EmailAddressSetting))]
	[JsonSerializable(typeof(StrongGrid.Models.EmailMessageActivity))]
	[JsonSerializable(typeof(StrongGrid.Models.EmailMessageSummary))]
	[JsonSerializable(typeof(StrongGrid.Models.EmailValidationAdditionalChecks))]
	[JsonSerializable(typeof(StrongGrid.Models.EmailValidationChecks))]
	[JsonSerializable(typeof(StrongGrid.Models.EmailValidationDomainChecks))]
	[JsonSerializable(typeof(StrongGrid.Models.EmailValidationLocalPartChecks))]
	[JsonSerializable(typeof(StrongGrid.Models.EmailValidationResult))]
	[JsonSerializable(typeof(StrongGrid.Models.EnforcedTlsSettings))]
	[JsonSerializable(typeof(StrongGrid.Models.Error))]
	[JsonSerializable(typeof(StrongGrid.Models.EventWebhookSettings))]
	[JsonSerializable(typeof(StrongGrid.Models.ExportJob))]
	[JsonSerializable(typeof(StrongGrid.Models.Field))]
	[JsonSerializable(typeof(StrongGrid.Models.FieldMetadata))]
	[JsonSerializable(typeof(StrongGrid.Models.FooterGlobalSettings))]
	[JsonSerializable(typeof(StrongGrid.Models.FooterSettings))]
	[JsonSerializable(typeof(StrongGrid.Models.GlobalSetting))]
	[JsonSerializable(typeof(StrongGrid.Models.GlobalSuppression))]
	[JsonSerializable(typeof(StrongGrid.Models.GoogleAnalyticsGlobalSettings))]
	[JsonSerializable(typeof(StrongGrid.Models.GoogleAnalyticsSettings))]
	[JsonSerializable(typeof(StrongGrid.Models.ImportJob))]
	[JsonSerializable(typeof(StrongGrid.Models.ImportJobRequest))]
	[JsonSerializable(typeof(StrongGrid.Models.ImportResults))]
	[JsonSerializable(typeof(StrongGrid.Models.InboundParseWebhookSettings))]
	[JsonSerializable(typeof(StrongGrid.Models.InvalidEmail))]
	[JsonSerializable(typeof(StrongGrid.Models.IpAddress))]
	[JsonSerializable(typeof(StrongGrid.Models.IpAddressesRemaining))]
	[JsonSerializable(typeof(StrongGrid.Models.IpPool))]
	[JsonSerializable(typeof(StrongGrid.Models.IpPoolAddress))]
	[JsonSerializable(typeof(StrongGrid.Models.Legacy.Campaign), TypeInfoPropertyName = "LegacyCampaign")]
	[JsonSerializable(typeof(StrongGrid.Models.Legacy.Contact), TypeInfoPropertyName = "LegacyContact")]
	[JsonSerializable(typeof(StrongGrid.Models.Legacy.CustomFieldMetadata), TypeInfoPropertyName = "LegacyCustomFieldMetadata")]
	[JsonSerializable(typeof(StrongGrid.Models.Legacy.Field), TypeInfoPropertyName = "LegacyField")]
	[JsonSerializable(typeof(StrongGrid.Models.Legacy.Field[]), TypeInfoPropertyName = "LegacyFieldArray")]
	[JsonSerializable(typeof(StrongGrid.Models.Legacy.FieldMetadata), TypeInfoPropertyName = "LegacyFieldMetadata")]
	[JsonSerializable(typeof(StrongGrid.Models.Legacy.ImportResult), TypeInfoPropertyName = "LegacyImportResult")]
	[JsonSerializable(typeof(StrongGrid.Models.Legacy.List), TypeInfoPropertyName = "LegacyList")]
	[JsonSerializable(typeof(StrongGrid.Models.Legacy.SearchCondition), TypeInfoPropertyName = "LegacySearchCondition")]
	[JsonSerializable(typeof(StrongGrid.Models.Legacy.Segment), TypeInfoPropertyName = "LegacySegment")]
	[JsonSerializable(typeof(StrongGrid.Models.LinkValidation))]
	[JsonSerializable(typeof(StrongGrid.Models.LinkValidationResults))]
	[JsonSerializable(typeof(StrongGrid.Models.List))]
	[JsonSerializable(typeof(StrongGrid.Models.MailAddress))]
	[JsonSerializable(typeof(StrongGrid.Models.MailContent))]
	[JsonSerializable(typeof(StrongGrid.Models.MailPersonalization))]
	[JsonSerializable(typeof(StrongGrid.Models.MailSettings))]
	[JsonSerializable(typeof(StrongGrid.Models.MonitorSettings))]
	[JsonSerializable(typeof(StrongGrid.Models.NewRelicSettings))]
	[JsonSerializable(typeof(StrongGrid.Models.OpenTrackingSettings))]
	[JsonSerializable(typeof(StrongGrid.Models.PaginationMetadata))]
	[JsonSerializable(typeof(StrongGrid.Models.ReverseDns))]
	[JsonSerializable(typeof(StrongGrid.Models.ReverseDnsValidation))]
	[JsonSerializable(typeof(StrongGrid.Models.ReverseDnsValidationResults))]
	[JsonSerializable(typeof(StrongGrid.Models.Search.SearchCriteria), TypeInfoPropertyName = "SearchSearchCriteria")]
	[JsonSerializable(typeof(StrongGrid.Models.Search.SearchCriteriaBetween), TypeInfoPropertyName = "SearchSearchCriteriaBetween")]
	[JsonSerializable(typeof(StrongGrid.Models.Search.SearchCriteriaContains), TypeInfoPropertyName = "SearchSearchCriteriaContains")]
	[JsonSerializable(typeof(StrongGrid.Models.Search.SearchCriteriaEqual), TypeInfoPropertyName = "SearchSearchCriteriaEqual")]
	[JsonSerializable(typeof(StrongGrid.Models.Search.SearchCriteriaGreaterEqual), TypeInfoPropertyName = "SearchSearchCriteriaGreaterEqual")]
	[JsonSerializable(typeof(StrongGrid.Models.Search.SearchCriteriaGreaterThan), TypeInfoPropertyName = "SearchSearchCriteriaGreaterThan")]
	[JsonSerializable(typeof(StrongGrid.Models.Search.SearchCriteriaIn), TypeInfoPropertyName = "SearchSearchCriteriaIn")]
	[JsonSerializable(typeof(StrongGrid.Models.Search.SearchCriteriaIsNotNull), TypeInfoPropertyName = "SearchSearchCriteriaIsNotNull")]
	[JsonSerializable(typeof(StrongGrid.Models.Search.SearchCriteriaIsNull), TypeInfoPropertyName = "SearchSearchCriteriaIsNull")]
	[JsonSerializable(typeof(StrongGrid.Models.Search.SearchCriteriaLessEqual), TypeInfoPropertyName = "SearchSearchCriteriaLessEqual")]
	[JsonSerializable(typeof(StrongGrid.Models.Search.SearchCriteriaLessThan), TypeInfoPropertyName = "SearchSearchCriteriaLessThan")]
	[JsonSerializable(typeof(StrongGrid.Models.Search.SearchCriteriaLike), TypeInfoPropertyName = "SearchSearchCriteriaLike")]
	[JsonSerializable(typeof(StrongGrid.Models.Search.SearchCriteriaNotBetween), TypeInfoPropertyName = "SearchSearchCriteriaNotBetween")]
	[JsonSerializable(typeof(StrongGrid.Models.Search.SearchCriteriaNotEqual), TypeInfoPropertyName = "SearchSearchCriteriaNotEqual")]
	[JsonSerializable(typeof(StrongGrid.Models.Search.SearchCriteriaNotIn), TypeInfoPropertyName = "SearchSearchCriteriaNotIn")]
	[JsonSerializable(typeof(StrongGrid.Models.Search.SearchCriteriaNotLike), TypeInfoPropertyName = "SearchSearchCriteriaNotLike")]
	[JsonSerializable(typeof(StrongGrid.Models.Search.SearchCriteriaUniqueArg), TypeInfoPropertyName = "SearchSearchCriteriaUniqueArg")]
	[JsonSerializable(typeof(StrongGrid.Models.Search.SearchCriteriaUniqueArgBetween), TypeInfoPropertyName = "SearchSearchCriteriaUniqueArgBetween")]
	[JsonSerializable(typeof(StrongGrid.Models.Search.SearchCriteriaUniqueArgEqual), TypeInfoPropertyName = "SearchSearchCriteriaUniqueArgEqual")]
	[JsonSerializable(typeof(StrongGrid.Models.Search.SearchCriteriaUniqueArgGreaterEqual), TypeInfoPropertyName = "SearchSearchCriteriaUniqueArgGreaterEqual")]
	[JsonSerializable(typeof(StrongGrid.Models.Search.SearchCriteriaUniqueArgGreaterThan), TypeInfoPropertyName = "SearchSearchCriteriaUniqueArgGreaterThan")]
	[JsonSerializable(typeof(StrongGrid.Models.Search.SearchCriteriaUniqueArgIn), TypeInfoPropertyName = "SearchSearchCriteriaUniqueArgIn")]
	[JsonSerializable(typeof(StrongGrid.Models.Search.SearchCriteriaUniqueArgLessEqual), TypeInfoPropertyName = "SearchSearchCriteriaUniqueArgLessEqual")]
	[JsonSerializable(typeof(StrongGrid.Models.Search.SearchCriteriaUniqueArgLessThan), TypeInfoPropertyName = "SearchSearchCriteriaUniqueArgLessThan")]
	[JsonSerializable(typeof(StrongGrid.Models.Search.SearchCriteriaUniqueArgLike), TypeInfoPropertyName = "SearchSearchCriteriaUniqueArgLike")]
	[JsonSerializable(typeof(StrongGrid.Models.Search.SearchCriteriaUniqueArgNotBetween), TypeInfoPropertyName = "SearchSearchCriteriaUniqueArgNotBetween")]
	[JsonSerializable(typeof(StrongGrid.Models.Search.SearchCriteriaUniqueArgNotEqual), TypeInfoPropertyName = "SearchSearchCriteriaUniqueArgNotEqual")]
	[JsonSerializable(typeof(StrongGrid.Models.Search.SearchCriteriaUniqueArgNotIn), TypeInfoPropertyName = "SearchSearchCriteriaUniqueArgNotIn")]
	[JsonSerializable(typeof(StrongGrid.Models.Search.SearchCriteriaUniqueArgNotLike), TypeInfoPropertyName = "SearchSearchCriteriaUniqueArgNotLike")]
	[JsonSerializable(typeof(StrongGrid.Models.Search.SearchCriteriaUniqueArgNotNull), TypeInfoPropertyName = "SearchSearchCriteriaUniqueArgNotNull")]
	[JsonSerializable(typeof(StrongGrid.Models.Search.SearchCriteriaUniqueArgNull), TypeInfoPropertyName = "SearchSearchCriteriaUniqueArgNull")]
	[JsonSerializable(typeof(StrongGrid.Models.Segment))]
	[JsonSerializable(typeof(StrongGrid.Models.SenderIdentity))]
	[JsonSerializable(typeof(StrongGrid.Models.SenderReputation))]
	[JsonSerializable(typeof(StrongGrid.Models.SingleSend))]
	[JsonSerializable(typeof(StrongGrid.Models.SingleSendEmailConfig))]
	[JsonSerializable(typeof(StrongGrid.Models.SingleSendSendTo))]
	[JsonSerializable(typeof(StrongGrid.Models.SpamCheckingSettings))]
	[JsonSerializable(typeof(StrongGrid.Models.SpamCheckSettings))]
	[JsonSerializable(typeof(StrongGrid.Models.SpamReport))]
	[JsonSerializable(typeof(StrongGrid.Models.Stat))]
	[JsonSerializable(typeof(StrongGrid.Models.Statistic))]
	[JsonSerializable(typeof(StrongGrid.Models.SubscriptionSettings))]
	[JsonSerializable(typeof(StrongGrid.Models.SubscriptionTrackingSettings))]
	[JsonSerializable(typeof(StrongGrid.Models.Subuser))]
	[JsonSerializable(typeof(StrongGrid.Models.Suppression))]
	[JsonSerializable(typeof(StrongGrid.Models.SuppressionGroup))]
	[JsonSerializable(typeof(StrongGrid.Models.Teammate))]
	[JsonSerializable(typeof(StrongGrid.Models.TeammateInvitation))]
	[JsonSerializable(typeof(StrongGrid.Models.Template))]
	[JsonSerializable(typeof(StrongGrid.Models.TemplateSettings))]
	[JsonSerializable(typeof(StrongGrid.Models.TemplateVersion))]
	[JsonSerializable(typeof(StrongGrid.Models.TrackingSettings))]
	[JsonSerializable(typeof(StrongGrid.Models.UnsubscribeOptions))]
	[JsonSerializable(typeof(StrongGrid.Models.UserCredits))]
	[JsonSerializable(typeof(StrongGrid.Models.UserProfile))]
	[JsonSerializable(typeof(StrongGrid.Models.ValidationResult))]
	[JsonSerializable(typeof(StrongGrid.Models.VerificationStatus))]
	[JsonSerializable(typeof(StrongGrid.Models.Webhooks.BouncedEvent), TypeInfoPropertyName = "WebhooksBouncedEvent")]
	[JsonSerializable(typeof(StrongGrid.Models.Webhooks.ClickedEvent), TypeInfoPropertyName = "WebhooksClickedEvent")]
	[JsonSerializable(typeof(StrongGrid.Models.Webhooks.DeferredEvent), TypeInfoPropertyName = "WebhooksDeferredEvent")]
	[JsonSerializable(typeof(StrongGrid.Models.Webhooks.DeliveredEvent), TypeInfoPropertyName = "WebhooksDeliveredEvent")]
	[JsonSerializable(typeof(StrongGrid.Models.Webhooks.DeliveryEvent), TypeInfoPropertyName = "WebhooksDeliveryEvent")]
	[JsonSerializable(typeof(StrongGrid.Models.Webhooks.DroppedEvent), TypeInfoPropertyName = "WebhooksDroppedEvent")]
	[JsonSerializable(typeof(StrongGrid.Models.Webhooks.EngagementEvent), TypeInfoPropertyName = "WebhooksEngagementEvent")]
	[JsonSerializable(typeof(StrongGrid.Models.Webhooks.Event), TypeInfoPropertyName = "WebhooksEvent")]
	[JsonSerializable(typeof(StrongGrid.Models.Webhooks.GroupResubscribeEvent), TypeInfoPropertyName = "WebhooksGroupResubscribeEvent")]
	[JsonSerializable(typeof(StrongGrid.Models.Webhooks.GroupUnsubscribeEvent), TypeInfoPropertyName = "WebhooksGroupUnsubscribeEvent")]
	/*
	 * Intentionally commenting out the following three lines because InboundEmailAttachment has a
	 * property of type 'Stream' which System.Text.Json.SourceGeneration can not handle.
	 * To make matters worse, you get an error regarding ReadOnlySpan<byte> which is confusing and not helpful.
	[JsonSerializable(typeof(StrongGrid.Models.Webhooks.InboundEmail), TypeInfoPropertyName = "WebhooksInboundEmail")]
	[JsonSerializable(typeof(StrongGrid.Models.Webhooks.InboundEmailAttachment), TypeInfoPropertyName = "WebhooksInboundEmailAttachment")]
	[JsonSerializable(typeof(StrongGrid.Models.Webhooks.InboundEmailEnvelope), TypeInfoPropertyName = "WebhooksInboundEmailEnvelope")]
	*/
	[JsonSerializable(typeof(StrongGrid.Models.Webhooks.IpPool), TypeInfoPropertyName = "WebhooksIpPool")]
	[JsonSerializable(typeof(StrongGrid.Models.Webhooks.Newsletter), TypeInfoPropertyName = "WebhooksNewsletter")]
	[JsonSerializable(typeof(StrongGrid.Models.Webhooks.OpenedEvent), TypeInfoPropertyName = "WebhooksOpenedEvent")]
	[JsonSerializable(typeof(StrongGrid.Models.Webhooks.ProcessedEvent), TypeInfoPropertyName = "WebhooksProcessedEvent")]
	[JsonSerializable(typeof(StrongGrid.Models.Webhooks.SpamReportEvent), TypeInfoPropertyName = "WebhooksSpamReportEvent")]
	[JsonSerializable(typeof(StrongGrid.Models.Webhooks.UnsubscribeEvent), TypeInfoPropertyName = "WebhooksUnsubscribeEvent")]
	[JsonSerializable(typeof(StrongGrid.Models.Webhooks.UrlOffset), TypeInfoPropertyName = "WebhooksUrlOffset")]
	[JsonSerializable(typeof(StrongGrid.Models.WhitelistedIp))]
	internal partial class StrongGridJsonSerializerContext : JsonSerializerContext
	{
	}
}
