using StrongGrid.Utilities;
using System.Text.Json.Serialization;

namespace StrongGrid.Models.Webhooks
{
	/// <summary>
	/// Recipient has opened the HTML message.
	/// You need to enable Open Tracking for getting this type of event.
	/// </summary>
	/// <seealso cref="StrongGrid.Models.Webhooks.EngagementEvent" />
	public class OpenedEvent : EngagementEvent
	{
		/// <summary>
		/// Initializes a new instance of the <see cref="OpenedEvent"/> class.
		/// </summary>
		public OpenedEvent()
		{
			EventType = EventType.Open;
		}

		/// <summary>
		/// Gets or sets the user agent.
		/// </summary>
		/// <value>
		/// The user agent.
		/// </value>
		[JsonPropertyName("useragent")]
		public string UserAgent { get; set; }

		/// <summary>
		/// Gets or sets the ip address of the recipient who engaged with the email.
		/// </summary>
		/// <value>
		/// The IP address.
		/// </value>
		[JsonPropertyName("ip")]
		public string IpAddress { get; set; }

		/// <summary>
		/// Gets or sets the categories.
		/// </summary>
		/// <value>
		/// The categories.
		/// </value>
		[JsonPropertyName("category")]
		[JsonConverter(typeof(CategoryConverter))]
		public string[] Categories { get; set; }

		/// <summary>
		/// Gets or sets the ID of the unsubscribe group the recipient's email address is included in.
		/// </summary>
		/// <remarks>
		/// ASM IDs correspond to the Id that is returned when you create an unsubscribe group.
		/// </remarks>
		/// <value>
		/// The asm group identifier.
		/// </value>
		[JsonPropertyName("asm_group_id")]
		public long? AsmGroupId { get; set; }

		/// <summary>
		/// Gets or sets the content type.
		/// </summary>
		/// <value>
		/// The content type.
		/// </value>
		[JsonPropertyName("sg_content_type")]
		public string ContentType { get; set; }

		/// <summary>
		/// Gets or sets a value indicating whether or not an open event has been generated by Apple Mail Privacy Protection.
		/// </summary>
		/// <remarks>
		/// When this field is set to true, it means that SendGrid has received signals indicating that a machine triggered the open event.
		/// When this field is false, it indicates that the event was triggered by a conventional open.
		/// This field was added as a response to the anonymization of some open event tracking caused by <a href="https://sendgrid.com/blog/apple-mail-privacy-protection/">Apple Mail Privacy Protection</a>.
		/// </remarks>
		/// <value>
		/// The machine open indicator.
		/// </value>
		[JsonProperty("sg_machine_open", NullValueHandling = NullValueHandling.Ignore)]
		public bool MachineOpen { get; set; }
	}
}
