using Newtonsoft.Json.Linq;
using Pathoschild.Http.Client;
using StrongGrid.Models;
using StrongGrid.Utilities;
using System.Threading;
using System.Threading.Tasks;

namespace StrongGrid.Resources
{
	/// <summary>
	/// Allows you to create and manage sender identities for Marketing Campaigns.
	/// </summary>
	/// <seealso cref="StrongGrid.Resources.Legacy.ISenderIdentities" />
	/// <remarks>
	/// See <a href="https://sendgrid.api-docs.io/v3.0/senders">SendGrid documentation</a> for more information.
	/// </remarks>
	public class SenderIdentities : ISenderIdentities
	{
		private const string _endpoint = "verified_senders";
		private readonly Pathoschild.Http.Client.IClient _client;

		/// <summary>
		/// Initializes a new instance of the <see cref="SenderIdentities" /> class.
		/// </summary>
		/// <param name="client">The HTTP client.</param>
		internal SenderIdentities(Pathoschild.Http.Client.IClient client)
		{
			_client = client;
		}

		/// <summary>
		/// Create a sender identity.
		/// </summary>
		/// <param name="nickname">The nickname.</param>
		/// <param name="from">From.</param>
		/// <param name="replyTo">The reply to.</param>
		/// <param name="address1">The address1.</param>
		/// <param name="address2">The address2.</param>
		/// <param name="city">The city.</param>
		/// <param name="state">The state.</param>
		/// <param name="zip">The zip.</param>
		/// <param name="country">The country.</param>
		/// <param name="cancellationToken">The cancellation token.</param>
		/// <returns>
		/// The <see cref="SenderIdentity" />.
		/// </returns>
		public Task<SenderIdentity> CreateAsync(string nickname, MailAddress from, MailAddress replyTo, string address1, string address2, string city, string state, string zip, string country, CancellationToken cancellationToken = default)
		{
			var data = CreateJObject(nickname, from, replyTo, address1, address2, city, state, zip, country);

			return _client
				.PostAsync(_endpoint)
				.WithJsonBody(data)
				.WithCancellationToken(cancellationToken)
				.AsObject<SenderIdentity>();
		}

		/// <summary>
		/// Retrieve a sender identity.
		/// </summary>
		/// <param name="senderIdentityId">The sender identity identifier.</param>
		/// <param name="cancellationToken">The cancellation token.</param>
		/// <returns>
		/// The <see cref="SenderIdentity" />.
		/// </returns>
		public Task<SenderIdentity> GetAsync(long senderIdentityId, CancellationToken cancellationToken = default)
		{
			return _client
				.GetAsync($"{_endpoint}/{senderIdentityId}")
				.WithCancellationToken(cancellationToken)
				.AsObject<SenderIdentity>();
		}

		/// <summary>
		/// Retrieve all sender identities.
		/// </summary>
		/// <param name="cancellationToken">Cancellation token.</param>
		/// <returns>
		/// An array of <see cref="SenderIdentity" />.
		/// </returns>
		public Task<SenderIdentity[]> GetAllAsync(CancellationToken cancellationToken = default)
		{
			return _client
				.GetAsync(_endpoint)
				.WithCancellationToken(cancellationToken)
				.AsObject<SenderIdentity[]>("results");
		}

		/// <summary>
		/// Determine which of SendGrid's verification processes have been completed for an account.
		/// </summary>
		/// <param name="cancellationToken">Cancellation token.</param>
		/// <returns>
		/// Two boolean values: the first value indicates whether a sender had been verified and the second value indicates whether a domain has been verified.
		/// </returns>
		public async Task<(bool SenderVerified, bool DomainVerified)> GetCompletedStepsAsync(CancellationToken cancellationToken = default)
		{
			var completedSteps = await _client
				.GetAsync($"{_endpoint}/steps_completed")
				.WithCancellationToken(cancellationToken)
				.AsRawJsonObject()
				.ConfigureAwait(false);

			var results = completedSteps["results"];
			var senderVerified = results["sender_verified"].Value<bool>();
			var domainVerified = results["domain_verified"].Value<bool>();

			return (senderVerified, domainVerified);
		}

		/// <summary>
		/// Get the list of domains known to implement DMARC and categorize them by failure type — hard failure or soft failure.
		/// </summary>
		/// <param name="cancellationToken">Cancellation token.</param>
		/// <returns>
		/// The list of domains known to implement DMARC.
		/// </returns>
		public Task<DomainsDmarc> GetDmarcDomains(CancellationToken cancellationToken = default)
		{
			return _client
				.GetAsync($"{_endpoint}/domains")
				.WithCancellationToken(cancellationToken)
				.AsSendGridObject<DomainsDmarc>("results");
		}

		/// <summary>
		/// Verify a sender request.
		/// </summary>
		/// <param name="verificationToken">The verification token which is generated by SendGrid and included in the verification email delivered to the address that is pending verification.</param>
		/// <param name="cancellationToken">Cancellation token.</param>
		/// <returns>
		/// The asynchronous task.
		/// </returns>
		public Task VerifySenderAsync(string verificationToken, CancellationToken cancellationToken = default)
		{
			return _client
				.GetAsync($"{_endpoint}/verify/{verificationToken}")
				.WithCancellationToken(cancellationToken)
				.AsMessage();
		}

		private static JObject CreateJObject(
			Parameter<string> nickname,
			Parameter<MailAddress> from,
			Parameter<MailAddress> replyTo,
			Parameter<string> address1,
			Parameter<string> address2,
			Parameter<string> city,
			Parameter<string> state,
			Parameter<string> zip,
			Parameter<string> country)
		{
			var result = new JObject();
			result.AddPropertyIfValue("nickname", nickname);
			result.AddPropertyIfValue("from_email", from.Value?.Email);
			result.AddPropertyIfValue("from_name", from.Value?.Name);
			result.AddPropertyIfValue("reply_to", replyTo.Value?.Email);
			result.AddPropertyIfValue("reply_to_name", replyTo.Value?.Name);
			result.AddPropertyIfValue("address", address1);
			result.AddPropertyIfValue("address2", address2);
			result.AddPropertyIfValue("city", city);
			result.AddPropertyIfValue("state", state);
			result.AddPropertyIfValue("zip", zip);
			result.AddPropertyIfValue("country", country);
			return result;
		}
	}
}
